[DEFAULT]
debug = true
verbose = true
secure_proxy_ssl_header = HTTP_X_FORWARDED_PROTO
public_endpoint = http://localhost:5000/

[database]
connection = mysql+pymysql://keystone:unime@iotronic-db/keystone

[token]
provider = fernet
expiration = 3600

[fernet_tokens]
key_repository = /etc/keystone/fernet-keys

[auth]
methods = external,password,token,oauth1,mapped,openid

[federation]
remote_id_attribute = HTTP_OIDC_ISS
trusted_dashboard = http://localhost/horizon/auth/websso/
#trusted_dashboard = http://localhost/horizon/auth/websso/
sso_callback_template = /etc/keystone/sso_callback.html

[cors]
allowed_origin = *

[policy]
driver = sql

[cache]
enabled = false

[assignment]
driver = sql

[role]
driver = sql

[resource]
driver = sql

[identity]
driver = sql
